"""criando tabelas

Revision ID: 9d3c5ba4915a
Revises: 
Create Date: 2024-10-19 17:10:09.354813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3c5ba4915a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('data_cadastro', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('avaliador', 'administrador', name='usuario_tipo'), nullable=False),
    sa.Column('data_cadastro', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("tipo IN ('avaliador', 'administrador')", name='check_tipo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projetos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo_projeto', sa.String(length=255), nullable=False),
    sa.Column('data_submissao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('em avaliação', 'aprovado', 'reprovado', name='status_projeto'), nullable=False),
    sa.Column('arquivo', sa.String(length=500), nullable=False),
    sa.Column('avaliador_id', sa.UUID(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('em avaliação', 'aprovado', 'reprovado')", name='check_status'),
    sa.ForeignKeyConstraint(['avaliador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('projeto_id', sa.UUID(), nullable=True),
    sa.Column('data_avaliacao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('feedback_qualitativo', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacoes')
    op.drop_table('projetos')
    op.drop_table('usuarios')
    op.drop_table('empresas')
    # ### end Alembic commands ###
